name: autokernel
dependencies:
  - pip
  - python=3.12
  - numpy
  - pip:
    - anthropic
    - python-dotenv
    - openai
    - openai-agents
    - cupy-cuda12x
    - pyopencl
    - pycuda
    - openai